name       : perl-test-requiresinternet
version    : 0.05
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/M/MA/MALLEN/Test-RequiresInternet-0.05.tar.gz : bba7b32a1cc0d58ce2ec20b200a7347c69631641e8cae8ff4567ad24ef1e833e
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Test::RequiresInternet - Easily test network connectivity
description: |
    This module is intended to easily test network connectivity before functional tests begin to non-local Internet resources.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
